// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineFoodOrderingSystem.Data;

#nullable disable

namespace OnlineFoodOrderingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250819044408_DropYourTableName")]
    partial class DropYourTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineFoodOrderingSystem.Models.RegisterVM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("mobileNumber")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("emailID")
                        .IsUnique();

                    b.HasIndex("roleID")
                        .IsUnique()
                        .HasDatabaseName("IX_RegisterVM_RoleID");

                    b.ToTable("registerUser");
                });

            modelBuilder.Entity("OnlineFoodOrderingSystem.Models.UserRole", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleId");

                    b.ToTable("userrole");
                });

            modelBuilder.Entity("OnlineFoodOrderingSystem.Models.RegisterVM", b =>
                {
                    b.HasOne("OnlineFoodOrderingSystem.Models.UserRole", "UserRoles")
                        .WithOne("RegisterVM")
                        .HasForeignKey("OnlineFoodOrderingSystem.Models.RegisterVM", "roleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RegisterVM_UserRole");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("OnlineFoodOrderingSystem.Models.UserRole", b =>
                {
                    b.Navigation("RegisterVM")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
